name: Deploy
  
on:
  workflow_run:
    workflows: ["Prepare"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'

jobs: 
  build-nuget:
    uses: bnayae/open-workflows/.github/workflows/dotnet-build-deploy-public-nuget.yml@main
    secrets:
      NUGET_PUBLISH: ${{ secrets.NUGET_PUBLISH }}
    with:
      build-config: Release
      dotnet-version: 7.0.x
      include-prerelease: false
      test-project: Bnaya.CSharp.AsyncExtensions.Tests
      test-switch: --filter category=ci

